name: Proto-gen

on:
    push:
        branches:
            - main
        paths:
        - 'apps/contracts/**'

jobs:
    publish:
        name: Publish job proto-gen
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20 
                registry-url: 'https://registry.npmjs.org'

            - name: Install deps
              run: npm ci

            - name: Install protobuf compiler
              run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

            - name: Generate TS Protobuf
              run: npm run proto:gen -w @ghostik/contracts

            - name: Publish package
              working-directory: apps/contracts
              run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
